import type { BibleQuestion } from "../types";

/**
 * Mission 5D expansion — Level 1 (Genesis 1-24: Creation, Noah, Abraham).
 * English only; verified: false pending human review (see the mission
 * report — AI-authored content stays draft per CLAUDE.md until a human
 * approves it). Existing Easy coverage for this level was already >=10,
 * so this batch fills Medium and Hard only.
 */
export const LEVEL_1_EXPANSION_EN: BibleQuestion[] = [
  {
    id: "exp-en-l1-m01",
    level: 1,
    category: "Creation",
    canonicalCategory: "Old Testament",
    book: "Genesis",
    testament: "old",
    chapter: 2,
    difficulty: "medium",
    correctIndex: 0,
    reference: "Genesis 2:2",
    tags: ["Creation"],
    verified: false,
    translations: {
      en: {
        question: "How many days did God take to create the world before resting?",
        choices: ["6", "7", "8", "5"],
        explanation: "God completed his work in six days and rested on the seventh, establishing the pattern for the Sabbath.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-m02",
    level: 1,
    category: "People",
    canonicalCategory: "People",
    book: "Genesis",
    testament: "old",
    chapter: 4,
    difficulty: "medium",
    correctIndex: 1,
    reference: "Genesis 4:8",
    tags: ["Cain and Abel"],
    verified: false,
    translations: {
      en: {
        question: "What did Cain do to his brother Abel out of jealousy?",
        choices: ["Exiled him", "Killed him", "Blessed him", "Enslaved him"],
        explanation: "Cain killed his brother Abel after God favored Abel's offering over his own.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-m03",
    level: 1,
    category: "Noah",
    canonicalCategory: "Old Testament",
    book: "Genesis",
    testament: "old",
    chapter: 7,
    difficulty: "medium",
    correctIndex: 1,
    reference: "Genesis 7:12",
    tags: ["Noah"],
    verified: false,
    translations: {
      en: {
        question: "How long did it rain during the flood in Noah's time?",
        choices: ["7 days", "40 days and nights", "100 days", "1 year"],
        explanation: "Rain fell on the earth for forty days and forty nights, flooding the whole world.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-m04",
    level: 1,
    category: "Noah",
    canonicalCategory: "Old Testament",
    book: "Genesis",
    testament: "old",
    chapter: 9,
    difficulty: "medium",
    correctIndex: 1,
    reference: "Genesis 9:13",
    tags: ["Noah"],
    verified: false,
    translations: {
      en: {
        question: "What sign did God give Noah that He would never again flood the whole earth?",
        choices: ["A dove", "A rainbow", "A star", "An altar"],
        explanation: "God set the rainbow in the clouds as the sign of His covenant never to destroy the earth by flood again.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-m05",
    level: 1,
    category: "Tower of Babel",
    canonicalCategory: "Old Testament",
    book: "Genesis",
    testament: "old",
    chapter: 11,
    difficulty: "medium",
    correctIndex: 1,
    reference: "Genesis 11:4-9",
    tags: ["Tower of Babel"],
    verified: false,
    translations: {
      en: {
        question: "Why did God confuse the people's language at the Tower of Babel?",
        choices: [
          "To punish idolatry",
          "Because they tried to build a tower to the heavens out of pride",
          "To end a war",
          "To reward obedience",
        ],
        explanation: "The people sought to make a name for themselves with a tower reaching the heavens, so God confused their language and scattered them.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-m06",
    level: 1,
    category: "Abraham",
    canonicalCategory: "Old Testament",
    book: "Genesis",
    testament: "old",
    chapter: 22,
    difficulty: "medium",
    correctIndex: 1,
    reference: "Genesis 22:2",
    tags: ["Abraham", "Isaac"],
    verified: false,
    translations: {
      en: {
        question: "What did God ask Abraham to do on Mount Moriah to test his faith?",
        choices: ["Build an altar", "Sacrifice his son Isaac", "Fast for 40 days", "Leave his home"],
        explanation: "God tested Abraham by asking him to offer his son Isaac; God provided a ram in Isaac's place at the last moment.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-m07",
    level: 1,
    category: "Sodom and Gomorrah",
    canonicalCategory: "Places",
    book: "Genesis",
    testament: "old",
    chapter: 19,
    difficulty: "medium",
    correctIndex: 1,
    reference: "Genesis 19:24-25",
    tags: ["Sodom and Gomorrah"],
    verified: false,
    translations: {
      en: {
        question: "What two cities did God destroy for their great wickedness in Abraham's time?",
        choices: ["Nineveh and Babylon", "Sodom and Gomorrah", "Jericho and Ai", "Tyre and Sidon"],
        explanation: "God rained down burning sulfur on Sodom and Gomorrah because of their great wickedness.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-m08",
    level: 1,
    category: "Sodom and Gomorrah",
    canonicalCategory: "Women",
    book: "Genesis",
    testament: "old",
    chapter: 19,
    difficulty: "medium",
    correctIndex: 1,
    reference: "Genesis 19:26",
    tags: ["Sodom and Gomorrah"],
    verified: false,
    translations: {
      en: {
        question: "Who disobeyed the angels' warning, looked back at Sodom, and turned into a pillar of salt?",
        choices: ["Sarah", "Lot's wife", "Hagar", "Rebekah"],
        explanation: "Lot's wife looked back at the destruction against the angels' warning and became a pillar of salt.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-m09",
    level: 1,
    category: "Lot",
    canonicalCategory: "People",
    book: "Genesis",
    testament: "old",
    chapter: 19,
    difficulty: "medium",
    correctIndex: 1,
    reference: "Genesis 19:15-16",
    tags: ["Lot"],
    verified: false,
    translations: {
      en: {
        question: "What was the name of Abraham's nephew rescued from Sodom before its destruction?",
        choices: ["Laban", "Lot", "Ishmael", "Eliezer"],
        explanation: "Angels led Abraham's nephew Lot and his family out of Sodom before it was destroyed.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-m10",
    level: 1,
    category: "Abraham",
    canonicalCategory: "Old Testament",
    book: "Genesis",
    testament: "old",
    chapter: 17,
    difficulty: "medium",
    correctIndex: 1,
    reference: "Genesis 17:5,15",
    tags: ["Abraham"],
    verified: false,
    translations: {
      en: {
        question: "What did God change Abram's and Sarai's names to as part of His covenant?",
        choices: ["Isaac and Rebekah", "Abraham and Sarah", "Israel and Rachel", "Jacob and Leah"],
        explanation: "God renamed Abram to Abraham ('father of many nations') and Sarai to Sarah as a sign of His covenant promise.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-h01",
    level: 1,
    category: "Noah",
    canonicalCategory: "Old Testament",
    book: "Genesis",
    testament: "old",
    chapter: 7,
    difficulty: "hard",
    correctIndex: 1,
    reference: "Genesis 7:6",
    tags: ["Noah"],
    verified: false,
    translations: {
      en: {
        question: "How old was Noah when the floodwaters came upon the earth?",
        choices: ["500", "600", "700", "950"],
        explanation: "Noah was six hundred years old when the flood came on the earth.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-h02",
    level: 1,
    category: "Noah",
    canonicalCategory: "Old Testament",
    book: "Genesis",
    testament: "old",
    chapter: 7,
    difficulty: "hard",
    correctIndex: 1,
    reference: "Genesis 7:2",
    tags: ["Noah"],
    verified: false,
    translations: {
      en: {
        question: "How many pairs of each clean animal did God tell Noah to bring onto the ark?",
        choices: ["Two", "Seven", "Twelve", "One"],
        explanation: "God instructed Noah to take seven pairs of every kind of clean animal, but only one pair of unclean animals.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-h03",
    level: 1,
    category: "Noah",
    canonicalCategory: "People",
    book: "Genesis",
    testament: "old",
    chapter: 11,
    difficulty: "hard",
    correctIndex: 2,
    reference: "Genesis 11:10-26",
    tags: ["Noah"],
    verified: false,
    translations: {
      en: {
        question: "Which of Noah's sons was an ancestor of Abraham, according to Genesis' genealogy?",
        choices: ["Ham", "Japheth", "Shem", "Canaan"],
        explanation: "Genesis 11's genealogy traces Abraham's line back through Shem, one of Noah's three sons.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-h04",
    level: 1,
    category: "Abraham",
    canonicalCategory: "Old Testament",
    book: "Genesis",
    testament: "old",
    chapter: 21,
    difficulty: "hard",
    correctIndex: 1,
    reference: "Genesis 12:4; 21:5",
    tags: ["Abraham", "Isaac"],
    verified: false,
    translations: {
      en: {
        question: "About how many years passed between Abraham leaving Haran and Isaac's birth?",
        choices: ["10 years", "25 years", "40 years", "5 years"],
        explanation: "Abraham was 75 when he left Haran (Genesis 12:4) and 100 when Isaac was born (Genesis 21:5) — about 25 years.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-h05",
    level: 1,
    category: "Abraham",
    canonicalCategory: "Places",
    book: "Genesis",
    testament: "old",
    chapter: 22,
    difficulty: "hard",
    correctIndex: 1,
    reference: "Genesis 22:2",
    tags: ["Abraham", "Isaac"],
    verified: false,
    translations: {
      en: {
        question: "In what region did God direct Abraham to offer Isaac as a sacrifice?",
        choices: ["Mount Sinai", "Moriah", "Mount Carmel", "Mount Nebo"],
        explanation: "God told Abraham to go to the region of Moriah to offer Isaac there.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-h06",
    level: 1,
    category: "Isaac",
    canonicalCategory: "Women",
    book: "Genesis",
    testament: "old",
    chapter: 24,
    difficulty: "hard",
    correctIndex: 1,
    reference: "Genesis 24:18-20",
    tags: ["Isaac", "Rebekah"],
    verified: false,
    translations: {
      en: {
        question: "What did Rebekah do at the well that fulfilled the sign Abraham's servant had prayed for?",
        choices: ["Refused to give water", "Drew water for him and all his camels", "Ran away", "Asked for payment"],
        explanation: "Rebekah drew water for the servant and all his camels, exactly matching the sign he had prayed for in choosing a wife for Isaac.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-h07",
    level: 1,
    category: "Abraham",
    canonicalCategory: "Law",
    book: "Genesis",
    testament: "old",
    chapter: 17,
    difficulty: "hard",
    correctIndex: 1,
    reference: "Genesis 17:10-14",
    tags: ["Abraham"],
    verified: false,
    translations: {
      en: {
        question: "What did God command as the everlasting sign of His covenant with Abraham's descendants?",
        choices: ["Building an altar every year", "Circumcision of every male", "Offering a lamb monthly", "Wearing special garments"],
        explanation: "God commanded that every male among Abraham's descendants be circumcised as the sign of the covenant.",
      },
    },
    translationStatus: { en: "machine" },
  },
  {
    id: "exp-en-l1-h08",
    level: 1,
    category: "Abraham",
    canonicalCategory: "People",
    book: "Genesis",
    testament: "old",
    chapter: 16,
    difficulty: "hard",
    correctIndex: 0,
    reference: "Genesis 16:15",
    tags: ["Abraham"],
    verified: false,
    translations: {
      en: {
        question: "What was the name of the son Hagar bore to Abraham?",
        choices: ["Ishmael", "Isaac", "Midian", "Esau"],
        explanation: "Hagar, Sarah's servant, bore Abraham a son whom he named Ishmael.",
      },
    },
    translationStatus: { en: "machine" },
  },
];
