import type { Question } from "./types";

// ---------------------------------------------------------------------------
// English question bank (source of truth / fallback language).
// Each category has 10 questions so the quiz continues through a full round.
// IMPORTANT: Bible references and any quoted/paraphrased Scripture text
// should be verified against a trusted translation before publishing.
// ---------------------------------------------------------------------------
export const QUESTIONS_EN: Question[] = [
  {
    id: "en-old-testament-001",
    categoryId: "old-testament",
    question: "Who led the Israelites out of slavery in Egypt?",
    choices: [
      "Joshua",
      "Aaron",
      "Moses",
      "Abraham",
    ],
    correctIndex: 2 as 0 | 1 | 2 | 3,
    reference: "Exodus 3:10",
    explanation: "God called Moses at the burning bush and sent him to deliver Israel from Pharaoh's rule.",
    difficulty: "Easy",
  },
  {
    id: "en-old-testament-002",
    categoryId: "old-testament",
    question: "What was the name of the garden where Adam and Eve lived?",
    choices: [
      "Gethsemane",
      "Eden",
      "Carmel",
      "Shiloh",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Genesis 2:8",
    explanation: "Genesis says God planted a garden in Eden and placed the man there.",
    difficulty: "Easy",
  },
  {
    id: "en-old-testament-003",
    categoryId: "old-testament",
    question: "Who built the ark before the flood?",
    choices: [
      "Noah",
      "Moses",
      "Jacob",
      "Samuel",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Genesis 6:13-22",
    explanation: "Noah obeyed God's instructions and built the ark to preserve life during the flood.",
    difficulty: "Easy",
  },
  {
    id: "en-old-testament-004",
    categoryId: "old-testament",
    question: "How many days did God use to create the heavens and the earth before resting?",
    choices: [
      "Five",
      "Six",
      "Seven",
      "Ten",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Genesis 1:31-2:2",
    explanation: "God completed His creative work in six days and rested on the seventh day.",
    difficulty: "Easy",
  },
  {
    id: "en-old-testament-005",
    categoryId: "old-testament",
    question: "Which sea did God divide for Israel to cross?",
    choices: [
      "Dead Sea",
      "Sea of Galilee",
      "Red Sea",
      "Mediterranean Sea",
    ],
    correctIndex: 2 as 0 | 1 | 2 | 3,
    reference: "Exodus 14:21-22",
    explanation: "God parted the Red Sea so Israel crossed on dry ground while escaping Egypt.",
    difficulty: "Easy",
  },
  {
    id: "en-old-testament-006",
    categoryId: "old-testament",
    question: "Who interpreted Pharaoh's dreams in Egypt?",
    choices: [
      "Joseph",
      "Daniel",
      "Moses",
      "Elijah",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Genesis 41:14-32",
    explanation: "God gave Joseph wisdom to interpret Pharaoh's dreams about seven years of plenty and famine.",
    difficulty: "Medium",
  },
  {
    id: "en-old-testament-007",
    categoryId: "old-testament",
    question: "What did God give Moses on Mount Sinai?",
    choices: [
      "The ark",
      "The Ten Commandments",
      "A crown",
      "A new language",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Exodus 31:18",
    explanation: "God gave Moses tablets of stone containing the commandments.",
    difficulty: "Easy",
  },
  {
    id: "en-old-testament-008",
    categoryId: "old-testament",
    question: "Who was swallowed by a great fish?",
    choices: [
      "Jonah",
      "Elisha",
      "Isaiah",
      "Hosea",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Jonah 1:17",
    explanation: "After Jonah fled from God's command, the Lord appointed a great fish to swallow him.",
    difficulty: "Easy",
  },
  {
    id: "en-old-testament-009",
    categoryId: "old-testament",
    question: "Which prophet confronted the prophets of Baal on Mount Carmel?",
    choices: [
      "Elijah",
      "Jeremiah",
      "Ezekiel",
      "Nathan",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "1 Kings 18:20-39",
    explanation: "Elijah challenged Israel to know that the Lord is God, and God answered by fire.",
    difficulty: "Medium",
  },
  {
    id: "en-old-testament-010",
    categoryId: "old-testament",
    question: "Who succeeded Moses as leader of Israel?",
    choices: [
      "Caleb",
      "Joshua",
      "Aaron",
      "Gideon",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Joshua 1:1-2",
    explanation: "After Moses died, God commanded Joshua to lead Israel into the promised land.",
    difficulty: "Easy",
  },
  {
    id: "en-new-testament-011",
    categoryId: "new-testament",
    question: "In which town was Jesus born?",
    choices: [
      "Nazareth",
      "Jerusalem",
      "Bethlehem",
      "Capernaum",
    ],
    correctIndex: 2 as 0 | 1 | 2 | 3,
    reference: "Luke 2:4-7",
    explanation: "Joseph and Mary traveled to Bethlehem for the census, and Jesus was born there.",
    difficulty: "Easy",
  },
  {
    id: "en-new-testament-012",
    categoryId: "new-testament",
    question: "Who baptized Jesus?",
    choices: [
      "Peter",
      "John the Baptist",
      "James",
      "Paul",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Matthew 3:13-17",
    explanation: "Jesus came to John at the Jordan River to be baptized.",
    difficulty: "Easy",
  },
  {
    id: "en-new-testament-013",
    categoryId: "new-testament",
    question: "Which book comes first in the New Testament?",
    choices: [
      "Mark",
      "Luke",
      "Matthew",
      "John",
    ],
    correctIndex: 2 as 0 | 1 | 2 | 3,
    reference: "Matthew 1:1",
    explanation: "Matthew is the first book in the New Testament order.",
    difficulty: "Easy",
  },
  {
    id: "en-new-testament-014",
    categoryId: "new-testament",
    question: "How many Gospels are in the New Testament?",
    choices: [
      "Two",
      "Three",
      "Four",
      "Five",
    ],
    correctIndex: 2 as 0 | 1 | 2 | 3,
    reference: "Matthew, Mark, Luke, John",
    explanation: "The four Gospels are Matthew, Mark, Luke, and John.",
    difficulty: "Easy",
  },
  {
    id: "en-new-testament-015",
    categoryId: "new-testament",
    question: "Who wrote many letters to churches in the New Testament?",
    choices: [
      "Paul",
      "Pilate",
      "Herod",
      "Nicodemus",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Romans 1:1",
    explanation: "Paul wrote several letters that teach churches about Christ and Christian living.",
    difficulty: "Easy",
  },
  {
    id: "en-new-testament-016",
    categoryId: "new-testament",
    question: "What happened on the day of Pentecost in Acts 2?",
    choices: [
      "The temple was built",
      "The Holy Spirit came",
      "Paul was born",
      "Jesus was baptized",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Acts 2:1-4",
    explanation: "The Holy Spirit filled the believers, and they began to speak as the Spirit enabled them.",
    difficulty: "Medium",
  },
  {
    id: "en-new-testament-017",
    categoryId: "new-testament",
    question: "Who was the first Christian martyr recorded in Acts?",
    choices: [
      "Stephen",
      "Philip",
      "Barnabas",
      "Timothy",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Acts 7:54-60",
    explanation: "Stephen faithfully witnessed about Jesus and was killed for his testimony.",
    difficulty: "Medium",
  },
  {
    id: "en-new-testament-018",
    categoryId: "new-testament",
    question: "Which apostle denied Jesus three times?",
    choices: [
      "John",
      "Peter",
      "Andrew",
      "Thomas",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Luke 22:54-62",
    explanation: "Peter denied knowing Jesus three times, then wept bitterly when he realized what happened.",
    difficulty: "Easy",
  },
  {
    id: "en-new-testament-019",
    categoryId: "new-testament",
    question: "What is the last book of the New Testament?",
    choices: [
      "Jude",
      "Revelation",
      "Hebrews",
      "Acts",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Revelation 1:1",
    explanation: "Revelation is the final book in the New Testament canon.",
    difficulty: "Easy",
  },
  {
    id: "en-new-testament-020",
    categoryId: "new-testament",
    question: "Who traveled with Paul on missionary journeys and encouraged believers?",
    choices: [
      "Barnabas",
      "Goliath",
      "Solomon",
      "Pharaoh",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Acts 13:2",
    explanation: "Barnabas was set apart with Paul for missionary work by the Holy Spirit.",
    difficulty: "Medium",
  },
  {
    id: "en-life-of-jesus-021",
    categoryId: "life-of-jesus",
    question: "Where did Jesus perform His first recorded miracle?",
    choices: [
      "Cana",
      "Capernaum",
      "Jericho",
      "Bethany",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "John 2:1-11",
    explanation: "At a wedding in Cana, Jesus turned water into wine, revealing His glory.",
    difficulty: "Medium",
  },
  {
    id: "en-life-of-jesus-022",
    categoryId: "life-of-jesus",
    question: "How many days was Jesus tempted in the wilderness?",
    choices: [
      "7",
      "12",
      "30",
      "40",
    ],
    correctIndex: 3 as 0 | 1 | 2 | 3,
    reference: "Matthew 4:1-2",
    explanation: "Jesus fasted forty days and nights and was tempted by the devil.",
    difficulty: "Easy",
  },
  {
    id: "en-life-of-jesus-023",
    categoryId: "life-of-jesus",
    question: "What did Jesus feed to five thousand men besides women and children?",
    choices: [
      "Seven loaves and fish",
      "Five loaves and two fish",
      "Manna only",
      "Bread and wine",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Matthew 14:17-21",
    explanation: "Jesus multiplied five loaves and two fish so the crowd ate and was satisfied.",
    difficulty: "Easy",
  },
  {
    id: "en-life-of-jesus-024",
    categoryId: "life-of-jesus",
    question: "Which disciple walked on water toward Jesus?",
    choices: [
      "John",
      "Peter",
      "James",
      "Philip",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Matthew 14:28-31",
    explanation: "Peter stepped out of the boat toward Jesus, but began sinking when he feared the wind.",
    difficulty: "Medium",
  },
  {
    id: "en-life-of-jesus-025",
    categoryId: "life-of-jesus",
    question: "Who climbed a sycamore tree to see Jesus?",
    choices: [
      "Zacchaeus",
      "Nicodemus",
      "Bartimaeus",
      "Jairus",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Luke 19:1-6",
    explanation: "Zacchaeus was short, so he climbed a tree to see Jesus passing through Jericho.",
    difficulty: "Easy",
  },
  {
    id: "en-life-of-jesus-026",
    categoryId: "life-of-jesus",
    question: "What prayer did Jesus teach His disciples?",
    choices: [
      "Hannah's prayer",
      "The Lord's Prayer",
      "Jabez's prayer",
      "Solomon's prayer",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Matthew 6:9-13",
    explanation: "Jesus taught His disciples to pray to the Father with reverence, dependence, and forgiveness.",
    difficulty: "Easy",
  },
  {
    id: "en-life-of-jesus-027",
    categoryId: "life-of-jesus",
    question: "Where did Jesus pray before His arrest?",
    choices: [
      "Gethsemane",
      "Cana",
      "Nazareth",
      "Emmaus",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Matthew 26:36-46",
    explanation: "Jesus prayed in Gethsemane, submitting Himself to the Father's will.",
    difficulty: "Easy",
  },
  {
    id: "en-life-of-jesus-028",
    categoryId: "life-of-jesus",
    question: "Who carried Jesus' cross for part of the way?",
    choices: [
      "Simon of Cyrene",
      "Joseph of Arimathea",
      "Barabbas",
      "Lazarus",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Luke 23:26",
    explanation: "Simon of Cyrene was compelled to carry the cross behind Jesus.",
    difficulty: "Medium",
  },
  {
    id: "en-life-of-jesus-029",
    categoryId: "life-of-jesus",
    question: "On which day did Jesus rise from the dead?",
    choices: [
      "The first day of the week",
      "The second day",
      "The Sabbath only",
      "The tenth day",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Luke 24:1-6",
    explanation: "The women came to the tomb on the first day of the week and found Jesus risen.",
    difficulty: "Easy",
  },
  {
    id: "en-life-of-jesus-030",
    categoryId: "life-of-jesus",
    question: "What did Jesus say is the greatest commandment?",
    choices: [
      "Love your neighbor only",
      "Love the Lord your God",
      "Fast every week",
      "Build many houses",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Matthew 22:37-38",
    explanation: "Jesus said the greatest commandment is to love the Lord with all your heart, soul, and mind.",
    difficulty: "Medium",
  },
  {
    id: "en-apostles-031",
    categoryId: "apostles",
    question: "Which apostle worked as a tax collector before following Jesus?",
    choices: [
      "Matthew",
      "Simon Peter",
      "Philip",
      "Bartholomew",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Matthew 9:9",
    explanation: "Jesus called Matthew while he sat at the tax booth, and Matthew followed Him.",
    difficulty: "Easy",
  },
  {
    id: "en-apostles-032",
    categoryId: "apostles",
    question: "Which two brothers were fishermen and sons of Zebedee?",
    choices: [
      "Peter and Andrew",
      "James and John",
      "Philip and Thomas",
      "Matthew and James",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Matthew 4:21-22",
    explanation: "James and John left their boat and father to follow Jesus.",
    difficulty: "Medium",
  },
  {
    id: "en-apostles-033",
    categoryId: "apostles",
    question: "Which apostle is often called doubting Thomas?",
    choices: [
      "Thomas",
      "James",
      "Jude",
      "Andrew",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "John 20:24-29",
    explanation: "Thomas wanted to see Jesus' wounds, and Jesus later invited him to believe.",
    difficulty: "Easy",
  },
  {
    id: "en-apostles-034",
    categoryId: "apostles",
    question: "Who was chosen to replace Judas Iscariot among the apostles?",
    choices: [
      "Matthias",
      "Barnabas",
      "Silas",
      "Mark",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Acts 1:23-26",
    explanation: "The believers cast lots, and Matthias was numbered with the eleven apostles.",
    difficulty: "Medium",
  },
  {
    id: "en-apostles-035",
    categoryId: "apostles",
    question: "Which apostle preached at Pentecost in Acts 2?",
    choices: [
      "Peter",
      "John",
      "Andrew",
      "Thomas",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Acts 2:14-41",
    explanation: "Peter explained the Scriptures and proclaimed Jesus as Lord and Christ.",
    difficulty: "Easy",
  },
  {
    id: "en-apostles-036",
    categoryId: "apostles",
    question: "Who was known as the apostle to the Gentiles?",
    choices: [
      "Paul",
      "James",
      "Peter",
      "Jude",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Romans 11:13",
    explanation: "Paul described his ministry as an apostle to the Gentiles.",
    difficulty: "Medium",
  },
  {
    id: "en-apostles-037",
    categoryId: "apostles",
    question: "Which apostle betrayed Jesus?",
    choices: [
      "Judas Iscariot",
      "John",
      "Philip",
      "Andrew",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Matthew 26:14-16",
    explanation: "Judas agreed to betray Jesus to the chief priests for silver.",
    difficulty: "Easy",
  },
  {
    id: "en-apostles-038",
    categoryId: "apostles",
    question: "Which apostle was Peter's brother?",
    choices: [
      "Andrew",
      "James",
      "Thomas",
      "Matthew",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "John 1:40-42",
    explanation: "Andrew first followed Jesus and brought his brother Simon Peter to Him.",
    difficulty: "Easy",
  },
  {
    id: "en-apostles-039",
    categoryId: "apostles",
    question: "Who wrote the book of Revelation?",
    choices: [
      "John",
      "Luke",
      "Paul",
      "Matthew",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Revelation 1:1-2",
    explanation: "John received and testified to the revelation of Jesus Christ.",
    difficulty: "Medium",
  },
  {
    id: "en-apostles-040",
    categoryId: "apostles",
    question: "Which apostle was a physician and companion of Paul?",
    choices: [
      "Luke",
      "Bartholomew",
      "Simon the Zealot",
      "Jude",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Colossians 4:14",
    explanation: "Luke is called the beloved physician and was associated with Paul's ministry.",
    difficulty: "Hard",
  },
  {
    id: "en-bible-characters-041",
    categoryId: "bible-characters",
    question: "Who defeated Goliath with a sling and stone?",
    choices: [
      "Saul",
      "David",
      "Samson",
      "Jonathan",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "1 Samuel 17:48-50",
    explanation: "David trusted the Lord and struck down the Philistine champion.",
    difficulty: "Easy",
  },
  {
    id: "en-bible-characters-042",
    categoryId: "bible-characters",
    question: "Who was thrown into a den of lions?",
    choices: [
      "Daniel",
      "Joseph",
      "Elijah",
      "Ezra",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Daniel 6:16-23",
    explanation: "Daniel remained faithful in prayer, and God shut the lions' mouths.",
    difficulty: "Easy",
  },
  {
    id: "en-bible-characters-043",
    categoryId: "bible-characters",
    question: "Who was the strongest man in Judges?",
    choices: [
      "Gideon",
      "Samson",
      "Boaz",
      "Jephthah",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Judges 14:5-6",
    explanation: "The Spirit of the Lord empowered Samson with extraordinary strength.",
    difficulty: "Easy",
  },
  {
    id: "en-bible-characters-044",
    categoryId: "bible-characters",
    question: "Who became queen and helped save her people?",
    choices: [
      "Ruth",
      "Esther",
      "Miriam",
      "Deborah",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Esther 4:14",
    explanation: "Esther was positioned to intercede for her people at a critical moment.",
    difficulty: "Easy",
  },
  {
    id: "en-bible-characters-045",
    categoryId: "bible-characters",
    question: "Who was Abraham's wife?",
    choices: [
      "Rebekah",
      "Sarah",
      "Rachel",
      "Leah",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Genesis 17:15-19",
    explanation: "God promised Abraham and Sarah a son named Isaac.",
    difficulty: "Easy",
  },
  {
    id: "en-bible-characters-046",
    categoryId: "bible-characters",
    question: "Who interpreted dreams in Babylon?",
    choices: [
      "Daniel",
      "Samuel",
      "Joseph",
      "Mordecai",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Daniel 2:27-28",
    explanation: "Daniel gave credit to God, who reveals mysteries.",
    difficulty: "Medium",
  },
  {
    id: "en-bible-characters-047",
    categoryId: "bible-characters",
    question: "Who said, 'Your people shall be my people, and your God my God'?",
    choices: [
      "Ruth",
      "Naomi",
      "Esther",
      "Hannah",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Ruth 1:16",
    explanation: "Ruth showed loyal love to Naomi and committed herself to the Lord.",
    difficulty: "Medium",
  },
  {
    id: "en-bible-characters-048",
    categoryId: "bible-characters",
    question: "Who was the mother of Samuel?",
    choices: [
      "Hannah",
      "Deborah",
      "Elizabeth",
      "Martha",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "1 Samuel 1:20",
    explanation: "Hannah prayed for a child and dedicated Samuel to the Lord.",
    difficulty: "Medium",
  },
  {
    id: "en-bible-characters-049",
    categoryId: "bible-characters",
    question: "Who rebuilt the walls of Jerusalem?",
    choices: [
      "Nehemiah",
      "Ezra",
      "Josiah",
      "Hezekiah",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Nehemiah 2:17-18",
    explanation: "Nehemiah led the people to rebuild the broken walls with faith and courage.",
    difficulty: "Medium",
  },
  {
    id: "en-bible-characters-050",
    categoryId: "bible-characters",
    question: "Who was sold by his brothers and later became a leader in Egypt?",
    choices: [
      "Joseph",
      "Benjamin",
      "Judah",
      "Reuben",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Genesis 37:28; 41:41",
    explanation: "Joseph suffered betrayal but God used him to preserve many lives.",
    difficulty: "Easy",
  },
  {
    id: "en-youth-challenge-051",
    categoryId: "youth-challenge",
    question: "Paul told Timothy not to let anyone look down on his what?",
    choices: [
      "Wealth",
      "Youth",
      "Family",
      "Homeland",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "1 Timothy 4:12",
    explanation: "Paul encouraged Timothy to be an example in speech, conduct, love, faith, and purity.",
    difficulty: "Easy",
  },
  {
    id: "en-youth-challenge-052",
    categoryId: "youth-challenge",
    question: "What should young people remember according to Ecclesiastes 12:1?",
    choices: [
      "Their Creator",
      "Their enemies",
      "Their money",
      "Their fame",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Ecclesiastes 12:1",
    explanation: "The verse calls young people to remember their Creator in the days of youth.",
    difficulty: "Medium",
  },
  {
    id: "en-youth-challenge-053",
    categoryId: "youth-challenge",
    question: "How can a young person keep their way pure according to Psalm 119:9?",
    choices: [
      "By wealth",
      "By guarding it according to God's word",
      "By popularity",
      "By strength",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Psalm 119:9",
    explanation: "God's word guides a young person's life toward purity and obedience.",
    difficulty: "Medium",
  },
  {
    id: "en-youth-challenge-054",
    categoryId: "youth-challenge",
    question: "Daniel and his friends refused to defile themselves with what?",
    choices: [
      "The king's food",
      "A golden crown",
      "A sword",
      "A scroll",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Daniel 1:8",
    explanation: "Daniel resolved not to defile himself and remained faithful in a foreign land.",
    difficulty: "Medium",
  },
  {
    id: "en-youth-challenge-055",
    categoryId: "youth-challenge",
    question: "Who was a young shepherd before becoming king?",
    choices: [
      "David",
      "Saul",
      "Solomon",
      "Samuel",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "1 Samuel 16:11-13",
    explanation: "David was called from the sheepfold and anointed by Samuel.",
    difficulty: "Easy",
  },
  {
    id: "en-youth-challenge-056",
    categoryId: "youth-challenge",
    question: "What did Jesus say to let the children do?",
    choices: [
      "Stay away",
      "Come to Him",
      "Build a tower",
      "Keep silent always",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Mark 10:14",
    explanation: "Jesus welcomed children and taught that the kingdom belongs to such as these.",
    difficulty: "Easy",
  },
  {
    id: "en-youth-challenge-057",
    categoryId: "youth-challenge",
    question: "Who served in the temple as a boy and heard God's voice?",
    choices: [
      "Samuel",
      "Isaac",
      "Jeremiah",
      "Josiah",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "1 Samuel 3:1-10",
    explanation: "Samuel learned to listen and respond, 'Speak, for your servant hears.'",
    difficulty: "Easy",
  },
  {
    id: "en-youth-challenge-058",
    categoryId: "youth-challenge",
    question: "What is a believer called to be in the world according to Matthew 5?",
    choices: [
      "Salt and light",
      "Thunder and rain",
      "Gold and silver",
      "Stone and clay",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Matthew 5:13-16",
    explanation: "Jesus taught His followers to shine through good works that glorify the Father.",
    difficulty: "Easy",
  },
  {
    id: "en-youth-challenge-059",
    categoryId: "youth-challenge",
    question: "What should believers do when they lack wisdom?",
    choices: [
      "Hide it",
      "Ask God",
      "Give up",
      "Trust luck",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "James 1:5",
    explanation: "James teaches that God gives wisdom generously to those who ask.",
    difficulty: "Easy",
  },
  {
    id: "en-youth-challenge-060",
    categoryId: "youth-challenge",
    question: "What kind of speech should come from believers?",
    choices: [
      "Only jokes",
      "Grace-filled speech",
      "Angry words",
      "Boasting",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Colossians 4:6",
    explanation: "Paul says speech should be gracious and seasoned with salt.",
    difficulty: "Medium",
  },
  {
    id: "en-psalms-proverbs-061",
    categoryId: "psalms-proverbs",
    question: "According to Proverbs, what is the beginning of wisdom?",
    choices: [
      "Hard work",
      "The fear of the Lord",
      "Good friends",
      "Education",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Proverbs 9:10",
    explanation: "Reverence for the Lord is the foundation of true wisdom.",
    difficulty: "Easy",
  },
  {
    id: "en-psalms-proverbs-062",
    categoryId: "psalms-proverbs",
    question: "Psalm 23 begins with which words?",
    choices: [
      "The Lord is my shepherd",
      "Blessed is the man",
      "Create in me",
      "God is our refuge",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Psalm 23:1",
    explanation: "David describes the Lord as a caring shepherd who provides and guides.",
    difficulty: "Easy",
  },
  {
    id: "en-psalms-proverbs-063",
    categoryId: "psalms-proverbs",
    question: "Which Psalm says, 'The Lord is my light and my salvation'?",
    choices: [
      "Psalm 1",
      "Psalm 27",
      "Psalm 51",
      "Psalm 150",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Psalm 27:1",
    explanation: "David declares confidence in the Lord as light, salvation, and stronghold.",
    difficulty: "Medium",
  },
  {
    id: "en-psalms-proverbs-064",
    categoryId: "psalms-proverbs",
    question: "Proverbs says to trust in the Lord with all your what?",
    choices: [
      "Mind",
      "Strength",
      "Heart",
      "Money",
    ],
    correctIndex: 2 as 0 | 1 | 2 | 3,
    reference: "Proverbs 3:5-6",
    explanation: "The proverb calls us to trust the Lord fully and acknowledge Him in all our ways.",
    difficulty: "Easy",
  },
  {
    id: "en-psalms-proverbs-065",
    categoryId: "psalms-proverbs",
    question: "Psalm 119 says God's word is a lamp to what?",
    choices: [
      "My path",
      "My house",
      "My city",
      "My crown",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Psalm 119:105",
    explanation: "God's word gives light and direction for the believer's steps.",
    difficulty: "Easy",
  },
  {
    id: "en-psalms-proverbs-066",
    categoryId: "psalms-proverbs",
    question: "Which Psalm is a prayer of repentance after David's sin?",
    choices: [
      "Psalm 2",
      "Psalm 51",
      "Psalm 90",
      "Psalm 121",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Psalm 51",
    explanation: "David asks God for mercy, cleansing, and a renewed heart.",
    difficulty: "Medium",
  },
  {
    id: "en-psalms-proverbs-067",
    categoryId: "psalms-proverbs",
    question: "Proverbs 15:1 says a soft answer turns away what?",
    choices: [
      "Wealth",
      "Wrath",
      "Sleep",
      "Rain",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Proverbs 15:1",
    explanation: "Gentle words can calm anger, while harsh words stir it up.",
    difficulty: "Medium",
  },
  {
    id: "en-psalms-proverbs-068",
    categoryId: "psalms-proverbs",
    question: "What does Psalm 46:1 call God?",
    choices: [
      "Our refuge and strength",
      "A distant king",
      "A hidden path",
      "A silent teacher",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Psalm 46:1",
    explanation: "God is presented as a present help in trouble.",
    difficulty: "Easy",
  },
  {
    id: "en-psalms-proverbs-069",
    categoryId: "psalms-proverbs",
    question: "Proverbs says pride goes before what?",
    choices: [
      "Peace",
      "Destruction",
      "Wisdom",
      "Harvest",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Proverbs 16:18",
    explanation: "Pride leads to downfall, but humility honors God.",
    difficulty: "Medium",
  },
  {
    id: "en-psalms-proverbs-070",
    categoryId: "psalms-proverbs",
    question: "Psalm 150 repeatedly calls everything that has breath to do what?",
    choices: [
      "Work",
      "Praise the Lord",
      "Fast",
      "Travel",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Psalm 150:6",
    explanation: "The final Psalm calls all living creatures to praise the Lord.",
    difficulty: "Easy",
  },
  {
    id: "en-faith-prayer-071",
    categoryId: "faith-prayer",
    question: "Hebrews 11:1 says faith is the assurance of things hoped for and evidence of what?",
    choices: [
      "Things not seen",
      "Things remembered",
      "Things promised by people",
      "Things written by kings",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Hebrews 11:1",
    explanation: "Faith trusts God's promises even before visible fulfillment.",
    difficulty: "Medium",
  },
  {
    id: "en-faith-prayer-072",
    categoryId: "faith-prayer",
    question: "Who prayed in the lions' den story even when the law forbade it?",
    choices: [
      "Daniel",
      "Moses",
      "David",
      "Ezra",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Daniel 6:10",
    explanation: "Daniel continued praying to God despite the king's decree.",
    difficulty: "Easy",
  },
  {
    id: "en-faith-prayer-073",
    categoryId: "faith-prayer",
    question: "Jesus taught believers to pray to whom?",
    choices: [
      "Our Father in heaven",
      "The angels",
      "The prophets",
      "The kings",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Matthew 6:9",
    explanation: "The Lord's Prayer begins by addressing God as Father in heaven.",
    difficulty: "Easy",
  },
  {
    id: "en-faith-prayer-074",
    categoryId: "faith-prayer",
    question: "According to James, the prayer of a righteous person is what?",
    choices: [
      "Powerful and effective",
      "Always loud",
      "Only private",
      "Impossible",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "James 5:16",
    explanation: "James teaches that earnest prayer has great effect.",
    difficulty: "Medium",
  },
  {
    id: "en-faith-prayer-075",
    categoryId: "faith-prayer",
    question: "What did Hannah pray for at Shiloh?",
    choices: [
      "A son",
      "A palace",
      "A battle victory",
      "A field",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "1 Samuel 1:10-11",
    explanation: "Hannah poured out her soul and asked the Lord for a child.",
    difficulty: "Easy",
  },
  {
    id: "en-faith-prayer-076",
    categoryId: "faith-prayer",
    question: "What did Jesus do early in the morning in Mark 1?",
    choices: [
      "Prayed in a solitary place",
      "Built a boat",
      "Wrote a letter",
      "Met Caesar",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Mark 1:35",
    explanation: "Jesus withdrew to a quiet place to pray before continuing ministry.",
    difficulty: "Medium",
  },
  {
    id: "en-faith-prayer-077",
    categoryId: "faith-prayer",
    question: "What should believers do instead of being anxious, according to Philippians 4?",
    choices: [
      "Pray with thanksgiving",
      "Hide from people",
      "Seek fame",
      "Stop working",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Philippians 4:6-7",
    explanation: "Paul teaches believers to bring requests to God with thanksgiving.",
    difficulty: "Easy",
  },
  {
    id: "en-faith-prayer-078",
    categoryId: "faith-prayer",
    question: "Who prayed, 'Lord, teach us to pray'?",
    choices: [
      "One of Jesus' disciples",
      "A Roman soldier",
      "A Pharisee only",
      "A shepherd",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Luke 11:1",
    explanation: "A disciple asked Jesus to teach them to pray, leading to Jesus' prayer instruction.",
    difficulty: "Medium",
  },
  {
    id: "en-faith-prayer-079",
    categoryId: "faith-prayer",
    question: "What did Jesus say faith like a mustard seed could move?",
    choices: [
      "A mountain",
      "A river",
      "A temple",
      "A city wall",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Matthew 17:20",
    explanation: "Jesus used the mustard seed to teach that genuine faith has powerful results.",
    difficulty: "Medium",
  },
  {
    id: "en-faith-prayer-080",
    categoryId: "faith-prayer",
    question: "In 1 Thessalonians 5, believers are told to pray how often?",
    choices: [
      "Without ceasing",
      "Only at night",
      "Once a year",
      "Only in church",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "1 Thessalonians 5:17",
    explanation: "Paul encourages a continual life of dependence and prayer.",
    difficulty: "Easy",
  },
  {
    id: "en-gospel-challenge-081",
    categoryId: "gospel-challenge",
    question: "According to Romans 10:9, what must one confess and believe to be saved?",
    choices: [
      "Jesus is Lord and God raised Him from the dead",
      "Good works earn salvation",
      "The law alone saves",
      "Fame proves faith",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Romans 10:9",
    explanation: "Paul teaches salvation through confessing Jesus as Lord and believing in His resurrection.",
    difficulty: "Medium",
  },
  {
    id: "en-gospel-challenge-082",
    categoryId: "gospel-challenge",
    question: "John 3:16 says God loved the world and gave whom?",
    choices: [
      "His only Son",
      "Moses",
      "An angel",
      "A king",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "John 3:16",
    explanation: "God's love is shown in giving His Son so believers may have eternal life.",
    difficulty: "Easy",
  },
  {
    id: "en-gospel-challenge-083",
    categoryId: "gospel-challenge",
    question: "What is the wages of sin according to Romans 6:23?",
    choices: [
      "Death",
      "Gold",
      "Wisdom",
      "Peace",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Romans 6:23",
    explanation: "Sin leads to death, but God's gift is eternal life in Christ Jesus.",
    difficulty: "Easy",
  },
  {
    id: "en-gospel-challenge-084",
    categoryId: "gospel-challenge",
    question: "What is the gift of God in Romans 6:23?",
    choices: [
      "Eternal life in Christ Jesus",
      "A new city",
      "Earthly riches",
      "A crown from Caesar",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Romans 6:23",
    explanation: "Eternal life is a gift from God, not something earned by human effort.",
    difficulty: "Easy",
  },
  {
    id: "en-gospel-challenge-085",
    categoryId: "gospel-challenge",
    question: "Who is called the Lamb of God by John the Baptist?",
    choices: [
      "Jesus",
      "Peter",
      "Elijah",
      "Moses",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "John 1:29",
    explanation: "John identified Jesus as the Lamb of God who takes away the sin of the world.",
    difficulty: "Easy",
  },
  {
    id: "en-gospel-challenge-086",
    categoryId: "gospel-challenge",
    question: "What did Jesus say He came to seek and save?",
    choices: [
      "The lost",
      "The rich only",
      "The powerful only",
      "The angels",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Luke 19:10",
    explanation: "Jesus described His mission as seeking and saving the lost.",
    difficulty: "Easy",
  },
  {
    id: "en-gospel-challenge-087",
    categoryId: "gospel-challenge",
    question: "According to Ephesians 2:8-9, salvation is by grace through what?",
    choices: [
      "Faith",
      "Money",
      "Strength",
      "Family name",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Ephesians 2:8-9",
    explanation: "Salvation is God's gift by grace through faith, not a result of works.",
    difficulty: "Medium",
  },
  {
    id: "en-gospel-challenge-088",
    categoryId: "gospel-challenge",
    question: "What did Jesus command His followers to make of all nations?",
    choices: [
      "Disciples",
      "Soldiers",
      "Merchants",
      "Kings",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Matthew 28:19-20",
    explanation: "The Great Commission calls believers to make disciples of all nations.",
    difficulty: "Medium",
  },
  {
    id: "en-gospel-challenge-089",
    categoryId: "gospel-challenge",
    question: "What message did Peter preach at Pentecost about Jesus?",
    choices: [
      "God made Him both Lord and Christ",
      "He was only a prophet",
      "He never rose",
      "He was unknown",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Acts 2:36",
    explanation: "Peter proclaimed that the crucified and risen Jesus is Lord and Christ.",
    difficulty: "Hard",
  },
  {
    id: "en-gospel-challenge-090",
    categoryId: "gospel-challenge",
    question: "What does 2 Corinthians 5:17 say someone is in Christ?",
    choices: [
      "A new creation",
      "A hidden servant",
      "A perfect scholar",
      "A Roman citizen",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "2 Corinthians 5:17",
    explanation: "In Christ, the old has passed away and new life has come.",
    difficulty: "Medium",
  },
  {
    id: "en-hard-questions-091",
    categoryId: "hard-questions",
    question: "How many books are in the Protestant Bible?",
    choices: [
      "63",
      "66",
      "72",
      "39",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Biblical canon",
    explanation: "The Protestant Bible contains 39 Old Testament books and 27 New Testament books.",
    difficulty: "Hard",
  },
  {
    id: "en-hard-questions-092",
    categoryId: "hard-questions",
    question: "Which minor prophet was told to marry Gomer?",
    choices: [
      "Hosea",
      "Joel",
      "Amos",
      "Micah",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Hosea 1:2-3",
    explanation: "Hosea's marriage served as a living picture of Israel's unfaithfulness and God's love.",
    difficulty: "Hard",
  },
  {
    id: "en-hard-questions-093",
    categoryId: "hard-questions",
    question: "Who was king of Judah when the book of the Law was found in the temple?",
    choices: [
      "Josiah",
      "Hezekiah",
      "Manasseh",
      "Uzziah",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "2 Kings 22:1-13",
    explanation: "During Josiah's reign, the book of the Law was found, leading to reform.",
    difficulty: "Hard",
  },
  {
    id: "en-hard-questions-094",
    categoryId: "hard-questions",
    question: "Which Gospel contains the 'I am' statements of Jesus most prominently?",
    choices: [
      "John",
      "Matthew",
      "Mark",
      "Luke",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "John 6:35; 8:12; 10:11",
    explanation: "John records several declarations where Jesus reveals His identity with 'I am' statements.",
    difficulty: "Hard",
  },
  {
    id: "en-hard-questions-095",
    categoryId: "hard-questions",
    question: "Who was Melchizedek king of?",
    choices: [
      "Salem",
      "Jericho",
      "Nineveh",
      "Tyre",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Genesis 14:18",
    explanation: "Melchizedek was king of Salem and priest of God Most High.",
    difficulty: "Hard",
  },
  {
    id: "en-hard-questions-096",
    categoryId: "hard-questions",
    question: "Which epistle emphasizes that faith without works is dead?",
    choices: [
      "James",
      "Romans",
      "Philemon",
      "2 John",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "James 2:17",
    explanation: "James teaches that living faith is shown through action.",
    difficulty: "Medium",
  },
  {
    id: "en-hard-questions-097",
    categoryId: "hard-questions",
    question: "What tribe was the apostle Paul from?",
    choices: [
      "Benjamin",
      "Judah",
      "Levi",
      "Naphtali",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Philippians 3:5",
    explanation: "Paul describes himself as from the tribe of Benjamin.",
    difficulty: "Hard",
  },
  {
    id: "en-hard-questions-098",
    categoryId: "hard-questions",
    question: "Who was the high priest when Samuel was a child?",
    choices: [
      "Eli",
      "Abiathar",
      "Zadok",
      "Aaron",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "1 Samuel 1:9; 3:1",
    explanation: "Samuel served the Lord under Eli before becoming a prophet.",
    difficulty: "Hard",
  },
  {
    id: "en-hard-questions-099",
    categoryId: "hard-questions",
    question: "Which book records the vision of the valley of dry bones?",
    choices: [
      "Ezekiel",
      "Daniel",
      "Isaiah",
      "Jeremiah",
    ],
    correctIndex: 0 as 0 | 1 | 2 | 3,
    reference: "Ezekiel 37:1-14",
    explanation: "Ezekiel saw dry bones come to life as a sign of God's restoring power.",
    difficulty: "Hard",
  },
  {
    id: "en-hard-questions-100",
    categoryId: "hard-questions",
    question: "In Revelation, how many churches are addressed in chapters 2 and 3?",
    choices: [
      "Five",
      "Seven",
      "Ten",
      "Twelve",
    ],
    correctIndex: 1 as 0 | 1 | 2 | 3,
    reference: "Revelation 2-3",
    explanation: "Seven churches in Asia Minor receive messages from the risen Christ.",
    difficulty: "Medium",
  },
];